import {JetBrains_Mono} from 'next/font/google'
import NavBar from "../components/NavBar";
import "./globals.css";
import Footer from '@/components/Footer';


const JetBrainsMono = JetBrains_Mono({ subsets: ['latin'],variable: "--jet-brains-mono"})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainsMono.variable} antialiased h-screen flex flex-col`}
      >
        <header>
          <NavBar/>
        </header>
        
        <main className='flex-grow flex flex-col max-w-screen-xl mx-auto'>
          {children}
          
        </main>
        <footer className='max-w-screen-xl mx-auto'>
          <Footer/>
        </footer>
    
      </body>
    </html>
  );
}
